# SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later
codecov:
  branch: master
  ci:
    - "!drone.nextcloud.com"
    - "!appveyor"

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: 0.5

comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default

github_checks:
    annotations: false

ignore:
  - "src/3rdparty"

