#cmakedefine PACKAGE "${APPLICATION_NAME}"
#cmakedefine VERSION "${APPLICATION_VERSION}"
#cmakedefine LOCALEDIR "${LOCALE_INSTALL_DIR}"
#cmakedefine DATADIR "${SHARE_INSTALL_PREFIX}"
#cmakedefine LIBDIR "${LIB_INSTALL_DIR}"
#cmakedefine PLUGINDIR "${PLUGIN_INSTALL_DIR}"
#cmakedefine SYSCONFDIR "${SYSCONF_INSTALL_DIR}"

#cmakedefine WITH_LOG4C 1
