option(LOCALBUILD "Local developer build" OFF)

if(LOCALBUILD)
    ## Only needed for local build
    message(STATUS "Building in LOCAL mode")
    
    set( APPLICATION_VIRTUALFILE_SUFFIX "${APPLICATION_SHORTNAME}_virtual" CACHE STRING "Virtual file suffix (not including the .)" FORCE)

    ## Windows Shell Extensions & MSI - IMPORTANT: Generate new GUIDs for custom builds with "guidgen" or "uuidgen"
    if(WIN32)
        # Context Menu
        set( WIN_SHELLEXT_CONTEXT_MENU_GUID      "{6B16FF7B-F242-4CE3-8FB9-F06EF127E0DC}" )

        # Overlays
        set( WIN_SHELLEXT_OVERLAY_GUID_ERROR     "{243D887B-9F74-41DD-BACA-BC5501AF10AC}" )
        set( WIN_SHELLEXT_OVERLAY_GUID_OK        "{2D88D499-3272-4A76-84BF-D252254B40D6}" )
        set( WIN_SHELLEXT_OVERLAY_GUID_OK_SHARED "{7BEF6B56-5B5B-4284-A70C-56D62254C97A}" )
        set( WIN_SHELLEXT_OVERLAY_GUID_SYNC      "{5F2F493D-A683-426F-925E-4CA25F17C4A9}" )
        set( WIN_SHELLEXT_OVERLAY_GUID_WARNING   "{7F256BB6-29D2-4E40-A6C4-E5E756E64C82}" )
    endif()

    if("${WHITELABEL_NAME}" STREQUAL "strato")
        set( APPLICATION_REV_DOMAIN "com.strato.hidrivenext.desktopclient" )
        set( APPLICATION_NAME       "STRATO HiDrive Next" )
        set( APPLICATION_SHORTNAME  "STRATOHiDriveNext" )
        set( APPLICATION_EXECUTABLE "strato-hidrive-next" )
        set( APPLICATION_CONFIG_NAME "STRATO-HiDrive-Next" )
        set( APPLICATION_ICON_NAME  "strato_hidrive_next" )
        set( APPLICATION_DOMAIN     "strato.com" )
        set( APPLICATION_UPDATE_URL "https://customerupdates.nextcloud.com/client/" CACHE STRING "URL for updater" FORCE)
        set( APPLICATION_HELP_URL   "" CACHE STRING "URL for the help menu" FORCE)
        set( APPLICATION_SERVER_URL "https://storage.ionos.fr" CACHE STRING "URL for the server to use. If entered, the UI field will be pre-filled with it" FORCE)
    elseif("${WHITELABEL_NAME}" STREQUAL "ionos")
        set( APPLICATION_REV_DOMAIN "com.ionos.hidrivenext.desktopclient" )
        set( APPLICATION_NAME       "IONOS HiDrive Next" )
        set( APPLICATION_SHORTNAME  "IONOSHiDriveNext" )
        set( APPLICATION_EXECUTABLE "ionos-hidrive-next" )
        set( APPLICATION_CONFIG_NAME "IONOS-HiDrive-Next" )
        set( APPLICATION_ICON_NAME  "ionos_hidrive_next" )
        set( APPLICATION_DOMAIN     "ionos.com" )
        set( APPLICATION_UPDATE_URL "https://customerupdates.nextcloud.com/client/" CACHE STRING "URL for updater" FORCE)
        set( APPLICATION_HELP_URL   "" CACHE STRING "URL for the help menu" FORCE)
        set( APPLICATION_SERVER_URL "https://storage.ionos.fr" CACHE STRING "URL for the server to use. If entered, the UI field will be pre-filled with it" FORCE)
    endif()

endif()

string(TOLOWER "${APPLICATION_NAME}" app_name_lower)
if(APPLE AND app_name_lower MATCHES "hidrive")
    set(APPLICATION_ICON_NAME "${APPLICATION_EXECUTABLE}-macOS")
    message("Using macOS-specific application icon: ${APPLICATION_ICON_NAME}")
endif()

if(APPLICATION_NAME STREQUAL "STRATO HiDrive Next")
    set( APPLICATION_VENDOR     "STRATO GmbH" )
    set( APPLICATION_REV_DOMAIN "com.strato.hidrivenext.desktopclient" )
    set( WIN_MSI_UI_DIALOG_BMP  "dialog_strato.bmp" )
    # MSI Upgrade Code (without brackets)
    set( WIN_MSI_UPGRADE_CODE   "F125E371-1E5D-424C-B738-70447A65F08C" )
    add_compile_definitions(STRATO_WL_BUILD)
    set( CFAPI_SHELLEXT_APPID_REG "{7D9A4B29-A898-4425-8CC6-E12C45D39D78}")
    set( CFAPI_SHELLEXT_CUSTOM_STATE_HANDLER_CLASS_ID "02D43837-7958-4DFB-9CB3-B7FB10276012" )
    set( CFAPI_SHELLEXT_THUMBNAIL_HANDLER_CLASS_ID "57822EDA-7186-4AD6-A113-5A7471A1F917" )
    set( APPLICATION_URI_HANDLER_SCHEME "strato")
elseif(APPLICATION_NAME STREQUAL "IONOS HiDrive Next")
    set( APPLICATION_VENDOR     "IONOS SE" )
    set( APPLICATION_REV_DOMAIN "com.ionos.hidrivenext.desktopclient" )
    set( WIN_MSI_UI_DIALOG_BMP  "dialog_ionos.bmp" )
    # MSI Upgrade Code (without brackets)
    set( WIN_MSI_UPGRADE_CODE   "6C9E5670-E8A9-4BBD-9BDF-D003794AC177" )
    add_compile_definitions(IONOS_WL_BUILD)
    set( CFAPI_SHELLEXT_APPID_REG "{8DA6F907-784F-4A7A-A704-83342A8C205E}")
    set( CFAPI_SHELLEXT_CUSTOM_STATE_HANDLER_CLASS_ID "A748032D-2EBF-40A3-BDC1-94C19D28A108" )
    set( CFAPI_SHELLEXT_THUMBNAIL_HANDLER_CLASS_ID "F8CE69E3-B804-4738-BF31-3CBD0E9A6674" )
    set( APPLICATION_URI_HANDLER_SCHEME "ionos")
endif()