set( APPLICATION_SHORTNAME  "owncloud" )
set( APPLICATION_NAME       "ownCloud" )
set( APPLICATION_EXECUTABLE "owncloud"        )
set( APPLICATION_DOMAIN     "owncloud.org"    )
set( APPLICATION_VENDOR     "ownCloud.org"    )
set( THEME_CLASS            "ownCloudTheme"   )
set( APPLICATION_REV_DOMAIN "org.owncloud.desktopclient" )
