sonar.projectKey=nextcloud_desktop
sonar.organization=nextcloud
sonar.projectBaseDir=..
sonar.sources=src
sonar.exclusions=3rdparty/**
sonar.sourceEncoding=UTF-8
sonar.cfamily.gcov.reportsPath=build/Testing/CoverageInfo
