######################################################################
# Automatically generated by qmake (2.01a) Do. Mär 21 15:22:28 2013
######################################################################
#
# SPDX-FileCopyrightText: 2015 ownCloud GmbH
# SPDX-License-Identifier: GPL-2.0-or-later

TEMPLATE = app
CONFIG -= app_bundle

DEPENDPATH += .
INCLUDEPATH += .
macx {
  LIBS += -framework CoreFoundation -framework CoreServices
}

# Input
HEADERS += ../../../src/libsync/utility.h
SOURCES += main.cpp ../../../src/libsync/utility.cpp
