######################################################################
# Automatically generated by qmake (2.01a) Do. Mär 21 15:22:28 2013
######################################################################

TEMPLATE = app
CONFIG -= app_bundle

DEPENDPATH += .
INCLUDEPATH += .
macx {
  LIBS += -framework CoreFoundation -framework CoreServices
}

# Input
HEADERS += ../../../src/libsync/utility.h
SOURCES += main.cpp ../../../src/libsync/utility.cpp
