# SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later
name: "🐞 Bug report"
description: "Help us to improve by reporting a bug"
title: "[Bug]: "
labels: ["bug", "0. Needs triage"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        ### 👍 Thank you for contributing to our project!
        * This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.
        * Please search the existing issues first, it's likely that your issue was already reported or even fixed.
            - Go to https://github.com/nextcloud and type any word in the top search/command bar. You probably see something like "We couldn’t find any repositories matching ..." then click "Issues" in the left navigation.
            - You can also filter by appending e. g. "state:open" to the search string.
            - More info on search syntax within github: https://help.github.com/articles/searching-issues
  - type: checkboxes
    id: before-posting
    attributes:
      label: "⚠️ Before submitting, please verify the following: ⚠️"
      description: All conditions are **required**. Your issue can be closed if these are checked incorrectly.
      options:
        - label: This is a **bug**, not a question or a configuration issue.
          required: true
        - label: This issue is **not** already reported on Github (I've searched it).
          required: true
        - label: Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
          required: true
        - label: I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Provide a description of the bug you're experiencing.
      value: |
        The share dialog is looking incomplete.
        ...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug.
      value: |
        1. Right click on the file
        2. Click on Share Options
        3. The share dialog does not display the option to share by e-mail
        ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
      value: |
        When clicking on the share dialog, share by e-mail should be an option.
        ...
    validations:
      required: true
  - type: input
    id: files
    attributes:
      label: Which files are affected by this bug
      description: Please, list **at least one file** that is affected by the issue reported. It will be easier to check the logs for errors.
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: Operating system
      description: In which operating system you are running the desktop client.
      options:
        - "Windows"
        - "macOS"
        - "Linux"
        - "Other (e.g. FreeBSD)"
    validations:
      required: true
  - type: input
    id: distro
    attributes:
      label: Which version of the operating system you are running.
      description: In case of Linux, provide the distribution + version.
      placeholder: Windows 11
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: Package
      description: Select installation method you used.
      options:
        - "Official Linux AppImage"
        - "Official Windows MSI"
        - "Official macOS 12+ universal pkg"
        - "Official macOS Virtual files 12+ universal pkg"
        - "Community FlatPak"
        - "Community SNAP package"
        - "Distro package manager"
        - "Compiled it myself"
        - "Other"
    validations:
      required: true
  - type: input
    id: server-version
    attributes:
      label: Nextcloud Server version
      description: Nextcloud Server version.
      placeholder: 28.0.5
    validations:
      required: true
  - type: input
    id: client-version
    attributes:
      label: Nextcloud Desktop Client version
      description: Nextcloud Desktop Client version.
      placeholder: 3.16.0
    validations:
      required: true
  - type: dropdown
    id: fresh
    attributes:
      label: Is this bug present after an update or on a fresh install?
      description: Select if bug is present after an update or on a fresh install.
      options:
        - "Updated from a minor version (ex. 3.16.1 to 3.16.2)"
        - "Updated to a major version (ex. 3.16.3 to 3.17.0)"
        - "Fresh desktop client install"
    validations:
      required: true
  - type: dropdown
    id: encryption
    attributes:
      label: Are you using the Nextcloud Server Encryption module?
      description: |
        Select if encryption is Enabled on your Nextcloud Server.
      options:
        - "Encryption is Enabled"
        - "Encryption is Disabled"
    validations:
      required: true
  - type: checkboxes
    id: users
    attributes:
      label: Are you using an external user-backend?
      description: |
        Select all user-backends Enabled on your Nextcloud Server.
        Describe in the "Additional info" section if you chose "Other".
      options:
      - label: "Default internal user-backend"
      - label: "LDAP/ Active Directory"
      - label: "SSO - SAML"
      - label: "Other"
    validations:
      required: true
  - type: textarea
    id: desktop-logs
    attributes:
      label: Nextcloud Server logs
      description: |
        Provide Nextcloud Server logs lines.
        Copy all contents from `data/nextcloud.log` or a RAW from `/settings/admin/logging` section:
        > NOTE: This will be automatically formatted into code or attach the file to the issue.
      render: shell
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Any additional information related to the issue.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## :warning: Desktop Client Logs
        Under the "General" settings, you can click on **"Create Debug Archive"** to pick the location of where the desktop client will export the logs and the database to a zip file: https://docs.nextcloud.com/server/latest/admin_manual/desktop/troubleshooting.html#create-debug-archive
        > Please attach the debug archive to this issue. You can edit it down to the bug report time window to reduce size.
        > Please note that the debug archive might include sensitive date. Review befor publishing
  - type: markdown
    attributes:
      value: |
        ## :camera: Screenshots
        Feel free to attach any screenshots that might help you to describe the bug your are experiencing.
