= Appendix A: Building the Client

This section explains how to build link:https://owncloud.org/download/#owncloud-desktop-client[the ownCloud Client] from source for all major platforms.
You should read this section if you want to develop for the desktop client.
Build instructions are subject to change as development proceeds.

NOTE: Please check the version for which you want to build.

These instructions are updated to work with version of the ownCloud Client.

[[compiling-via-ownbrander]]
== Compiling via ownBrander

If you don’t want to go through the trouble of doing all the compile work manually, you can use
https://doc.owncloud.org/branded_clients/[ownBrander] to create installer images for all platforms.

[[getting-source-code]]
== Getting the Source Code

The xref:generic-build-instructions[generic build instructions] pull the latest code directly from GitHub, and work on xref:linux[Linux], xref:macos[Mac OS X], and xref:windows-development-build[Windows].

[[linux]]
== Linux

For the published desktop clients we link against QT5 dependencies from our own repositories so that we can have the same versions on all distributions.
This chapter shows you how to build the client yourself with this setup.
If you want to use the QT5 dependencies from your system, see the next chapter.

You may wish to use source packages for your Linux distribution, as these give you the exact sources from which the binary packages are built.
These are hosted on the http://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client[ownCloud repository from OBS].
Go to the http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/[Index of repositories] to see all the Linux client repositories.

[NOTE]
====
To get the `.deb` source packages, add the source repository for your Debian or Ubuntu version, as in the following example for Debian 9:

[source,console]
....
# Run as root
echo 'deb-src http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/ /' >> /etc/apt/sources.list.d/owncloud-client.list
....
====

Install the dependencies using the following commands for your specific Linux distribution.
Make sure the repositories for source packages are enabled.
These are:

[options="header"]
|===
| Distribution | Installation Instructions
| Debian/Ubuntu | `apt update; apt build-dep owncloud-client`
| openSUSE/SLES | `zypper ref; zypper si -d owncloud-client`
| Fedora/CentOS/RHEL | `yum install yum-utils; yum-builddep owncloud-client`
|===

Follow the xref:generic-build-instructions[generic build instructions], starting with step 2.

[[linux-with-system-dependencies]]
== Linux with System Dependencies

Build sources from a GitHub checkout with dependencies provided by your Linux distribution.
While this allows more freedom for development, it does not exactly represent what we ship as packages.
See above for how to recreate packages from source.

[NOTE]
====
To get the source dependencies on Debian and Ubuntu, run the following command:

[source,console]
....
sudo apt install qtdeclarative5-dev libinotifytools-dev \
  qt5keychain-dev libqt5webkit5-dev python-sphinx \
  libsqlite3-dev
....
====

Follow the xref:generic-build-instructions[generic build instructions], starting with step 1.

[[macos]]
== macOS

In addition to needing Xcode (along with the command line tools), developing in the macOS environment requires extra dependencies.
You can install these dependencies through http://www.macports.org[MacPorts] or http://mxcl.github.com/homebrew/[Homebrew].
These dependencies are required only on the build machine, because non-standard libs are deployed in the app bundle.

The tested and preferred way to develop in this environment is through the use of http://mxcl.github.com/homebrew/[HomeBrew].
The ownCloud team has its own repository containing non-standard recipes.
To set up your build environment for development using http://mxcl.github.com/homebrew/[HomeBrew]:

. Install xref:https://developer.apple.com/xcode/[Xcode].
. Install Xcode command line tools using `xcode-select –install`.
. Install Homebrew using `/usr/bin/ruby -e $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)`.
. Add the ownCloud repository using the command `brew tap owncloud/owncloud`
. Install a Qt5 version, ideally from from 5.10.1, using the command `brew install qt5`.
. Install any missing dependencies, using the command: `brew install $(brew deps owncloud-client)`.

[start=7]
. Install qtkeychain by running `git clone https://github.com/frankosterfeld/qtkeychain.git`. Make sure you make the
same install prefix as later while building the client e.g., `-DCMAKE_INSTALL_PREFIX=/Path/to/client/../install`.
. For compilation of the client, follow the xref:generic-build-instructions[generic build instructions].
. Install the http://s.sudre.free.fr/Software/Packages/about.html[Packages] package creation tool.
. In the build directory, run `admin/osx/create_mac.sh <CMAKE_INSTALL_DIR> <build dir> <installer sign identity>`.
  If you have a developer signing certificate, you can specify its Common Name as a third parameter (use quotes) to have the package signed automatically.

[NOTE]
====
Contrary to earlier versions, version 1.7 and later are packaged as a `pkg` installer.
Do not call `make package` at any time when compiling for OS X, as this will build a disk image, which will not work correctly.
====

[[windows-development-build]]
== Windows Development Build

If you want to test some changes and deploy them locally, you can build natively on Windows using xref:http://www.mingw.org/[MinGW].
If you want to generate an installer for deployment, please follow link:[Windows Installer Build (Cross-Compile)] instead.

. Get the required dependencies

* Make sure that you have http://www.cmake.org/download[CMake] and http://git-scm.com[Git].
* Download the http://www.qt.io/download[Qt] MinGW package. You will use the MinGW version bundled with it.
* Download an http://slproweb.com/products/Win32OpenSSL.html[OpenSSL Windows Build] (the non-'Light' version)
. Get the https://github.com/frankosterfeld/qtkeychain[QtKeychain] sources as well as the latest versions of the ownCloud client from Git as follows:
+
....
git clone https://github.com/frankosterfeld/qtkeychain.git
git clone git://github.com/owncloud/client.git
....

[start=3]
. Open the Qt MinGW shortcut console from the Start Menu
. Make sure that OpenSSL’s `bin` directory as well as your QtKeychain source directories are in your PATH. This will allow CMake to find the library and headers, as well as allow the ownCloud client to find the
DLLs at runtime:
+
[source,console]
....
set PATH=C:\<OpenSSL Install Dir>\bin;%PATH%
set PATH=C:\<qtkeychain Clone Dir>;%PATH%
....

[start=5]
. Build qtkeychain *directly in the source directory* so that the DLL
is built in the same directory as the headers to let CMake find them
together through PATH:
+
[source,console]
....
cd <qtkeychain Clone Dir>
cmake -G "MinGW Makefiles" .
mingw32-make
cd ..
....

[start=6]
. Create the build directory:
+
[source,console]
....
mkdir client-build
cd client-build
....

[start=7]
. Build the client:
+
[source,console]
....
cmake -G "MinGW Makefiles" -DNO_SHIBBOLETH=1 ../client
mingw32-make
....
+
You can try using ninja to build in parallel using `cmake -G Ninja ../client` and `ninja` instead.
Refer to the xref:generic-build-instructions[generic build instructions] section for additional options.
The ownCloud binary will appear in the `bin` directory.

[[windows-installer-build-cross-compile]]
== Windows Installer Build (Cross-Compile)

Due to the large number of dependencies, building the client installer for Windows is *currently only officially supported on openSUSE*, by using the MinGW cross compiler.
You can set up any currently supported version of openSUSE in a virtual machine if you do not have it installed already.

In order to make setup simple, you can use the provided Dockerfile to build your own image.

. Assuming you are in the root of the ownCloud Client’s source tree, you can build an image from this Dockerfile like this:
+
[source,console]
....
cd admin/win/docker
docker build . -t owncloud-client-win32:<version>
....
+
Replace `<version>` by the version of the client you are building, e.g., for the release of the client that this document describes.
If you do not wish to use docker, you can run the commands in `RUN` manually in a shell, e.g., to create your own build environment in a virtual machine.
+
Docker images are specific to releases.
Newer releases may have different dependencies, and thus require a later version of the docker image!
Always pick the docker image fitting your release of ownCloud client!


[start=2]
. From within the source tree Run the docker instance:
+
[source,console]
....
docker run -v "$PWD:/home/user/client" owncloud-client-win32:<version> \
   /home/user/client/admin/win/docker/build.sh client/  $(id -u)
....
+
It will run the build, create an NSIS based installer, as well as run tests.
You will find the resulting binary in an newly created `build-win32` subfolder.
+
If you do not wish to use docker, and ran the `RUN` commands above in a virtual machine, you can run the indented commands in the lower section of `build.sh` manually in your source tree.

[start=3]
. Finally, you should sign the installer to avoid warnings upon installation. This requires a https://msdn.microsoft.com/en-us/library/ie/ms537361%28v=vs.85%29.aspx[Microsoft Authenticode] Certificate `osslsigncode` to sign the installer:
+
[source,console]
....
osslsigncode -pkcs12 $HOME/.codesign/packages.pfx -h sha256 \
    -pass yourpass \
    -n "ACME Client" \
    -i "http://acme.com" \
    -ts "http://timestamp.server/" \
    -in ${unsigned_file} \
    -out ${installer_file}
....
+
For `-in`, use the URL to the time stamping server provided by your CA along with the Authenticode certificate. Alternatively, you may use the official Microsoft `signtool` utility on Microsoft Windows.

TIP: If you’re familiar with Docker, you can use the version of `osslsigncode` that is part of the docker image.

[[generic-build-instructions]]
== Generic Build Instructions

To build the most up-to-date version of the client:

. Clone the latest versions of the client from http://git-scm.com[Git] as follows:
+
[source,console]
....
git clone git://github.com/owncloud/client.git
cd client
# master this default, but you can also check out a tag like v2.4.1
git checkout master
git submodule init
git submodule update
....

[start=2]
. Create the build directory:
+
[source,console]
....
mkdir client-build
cd client-build
....

[start=3]
. Configure the client build:
+
[source,console]
....
cmake -DCMAKE_PREFIX_PATH=/opt/ownCloud/qt-5.10.1 -DCMAKE_INSTALL_PREFIX=/Users/path/to/client/../install/  -DNO_SHIBBOLETH=1 ..
....
+
For Linux builds (using QT5 libraries via build-dep) a typical setting is `-DCMAKE_PREFIX_PATH=/opt/ownCloud/qt-5.10.1/` - version number may vary.
For Linux builds using system dependencies `-DCMAKE_PREFIX_PATH` is not needed.
You must use absolute paths for the `include` and `library` directories.
+
On Mac OS X, you need to specify `-DCMAKE_INSTALL_PREFIX=target`, where `target` is a private location, i.e. in parallel to your build dir by specifying `../install`.
+
qtkeychain must be compiled with the same prefix e.g., `-DCMAKE_INSTALL_PREFIX=/Users/path/to/client/../install/`

[start=4]
. Call `make`. The ownCloud binary will appear in the `bin` directory.

[start=5]
. (Optional) Call `make install` to install the client to the `/usr/local/bin` directory.
The following are known CMake parameters:

* `QTKEYCHAIN_LIBRARY=/path/to/qtkeychain.dylib -DQTKEYCHAIN_INCLUDE_DIR=/path/to/qtkeychain/`
  Used for stored credentials. When compiling with Qt5, the library is
  called `qt5keychain.dylib.` You need to compile QtKeychain with the
  same Qt version. If you install QtKeychain into the CMAKE_PREFIX_PATH
  then you don’t need to specify the path manually.

* `WITH_DOC=TRUE`: Creates doc and manpages through running `make`; also adds install statements, providing the ability to install using `make install`.

* `CMAKE_PREFIX_PATH=/path/to/Qt5.10.1/5.10.1/yourarch/lib/cmake/`: Builds using that Qt version.

* `CMAKE_INSTALL_PREFIX=path`: Set an install prefix. This is mandatory on Mac OS
