// This file is generated by kxml_compiler from occinfo.xml.
// All changes you do to this file will be lost.
#ifndef OCCINFO_H
#define OCCINFO_H

#include <QString>
#include <QDomElement>
#include <QXmlStreamWriter>

namespace Mirall {

class Owncloudclient
{
  public:
    void setVersion( const QString &v );
    QString version() const;
    void setVersionstring( const QString &v );
    QString versionstring() const;
    void setWeb( const QString &v );
    QString web() const;
    /**
      Parse XML object from DOM element.
     */
    static Owncloudclient parseElement( const QDomElement &element, bool *ok );
    void writeElement( QXmlStreamWriter &xml );
    static Owncloudclient parseFile( const QString &filename, bool *ok );
    static Owncloudclient parseString( const QString &xml, bool *ok );
    bool writeFile( const QString &filename );

  private:
    QString mVersion;
    QString mVersionstring;
    QString mWeb;
};

} // namespace Mirall

#endif
