# SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later
name: Clang Format Checker
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  build:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: cpp-linter/cpp-linter-action@77c390c5ba9c947ebc185a3e49cc754f1558abb5 # v2.18.0
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: file
        lines-changed-only: true
        version: 14
    - name: Fail fast?!
      if: steps.linter.outputs.checks-failed > 0
      run: echo "Some files failed the linting checks!"
