# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later

name: mac-crafter CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  tests:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft }}
    name: Test mac-crafter
    timeout-minutes: 15
    runs-on: macos-26
    defaults:
      run:
        working-directory: admin/osx/mac-crafter
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: latest-stable

      - name: Run tests
        run: swift test
